# Generated by Django 4.0.5 on 2022-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('executed_at', models.DateField()),
            ],
        ),
    ]
